Update compress.bash
regalstreak/skadoosh pull request #58
Opened 2016-09-28 13:39 UTC by mestreian

2016-09-28 13:41 UTC, MSF-Jarvis commented on compress.bash
> +manifest=https://github.com/AOSP-RRO/manifest -b nougat
YOU DON'T SPECIFY A BRANCH HERE

2016-09-28 13:44 UTC, mestreian commented on compress.bash
> +manifest=https://github.com/AOSP-RRO/manifest -b nougat
the branch is nougat, -b nougat is the branch.
https://github.com/AOSP-RRO/manifest

2016-09-30 06:40 UTC, msfjarvis requested changes

2016-09-30 06:40 UTC, msfjarvis commented on compress.bash
> +branch=android-7.0.0_r6
Branch name belongs HERE, the `-b nougat` there is pure bullshit

2016-09-30 06:41 UTC, MSF-Jarvis commented on compress.bash
> +branch=android-7.0.0_r6
I don't see such a branch name on the manifest. Have you even bothered to check?

2016-10-11 12:41 UTC, closed without merging